// import 'package:elites_certificate/Mentorpages/autogeneratedemail.dart';
import 'package:flutter/material.dart';
import 'package:elites_certificate/signin/loginpage.dart';

import 'package:firebase_core/firebase_core.dart';
import 'package:firebase_auth/firebase_auth.dart';
import 'firebase_options.dart';
import 'package:elites_certificate/Mentorpages/mentorhome.dart';
import 'package:elites_certificate/pages/homepage.dart';
// import 'package:elites_certificate/admin/adminhome.dart';

// void main() {
//   runApp(MaterialApp(
//     home: AutoGeneratedEmail(),
//   ));
// }

// void main() async {
//   WidgetsFlutterBinding.ensureInitialized();
//   await Firebase.initializeApp(
//     options: DefaultFirebaseOptions.currentPlatform,
//   );
//     i am trying use the dart should see what i will happend runApp(MyApp());
// }

// class MyApp extends StatelessWidget {
//   @override
//   Widget build(BuildContext context) {
//     return MaterialApp(
//       title: 'Your App Title',
//       home:
//           AdminHomePage(), // Replace HomeScreen with your initial screen widget
//     );
//   }
// }

Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      debugShowCheckedModeBanner: false,
      home: AuthenticationWrapper(),
      routes: {
        '/login': (context) => LoginPage(),
        '/home': (context) => MyHomePage(),
      },
    );
  }
}

class AuthenticationWrapper extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    final User? user = FirebaseAuth.instance.currentUser;

    if (user != null) {
      // User is signed in
      String userEmail = user.email ?? "";

      if (userEmail.endsWith("@nitte.edu.in")) {
        return MentorHomePage();
      } else if (userEmail.endsWith("@nmamit.in")) {
        return MyHomePage();
      } else {
        return LoginPage();
      }
    } else {
      return LoginPage();
    }
  }
}
