import 'package:mailer/mailer.dart';
import 'package:mailer/smtp_server.dart';
import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:firebase_auth/firebase_auth.dart';

class AutoGeneratedEmail {
  final Map<String, dynamic> filesData;

  AutoGeneratedEmail({
    required this.filesData,
  });

  Future<void> sendEmail(username, password, recipientEmail) async {
    final User? user = FirebaseAuth.instance.currentUser;
    final String? mentor = user?.email;

    final smtpServer = gmail(username, password);
    print("Navi" + username);
    print("${filesData['email']}");
    final message = Message()
      ..from = Address(username)
      ..recipients.add(recipientEmail)
      ..subject = 'Certificate Approved by: ${mentor}  (Do not reply)'
      ..text = 'This is an autogenerated email. Do not reply'
      ..html = '''
        <h3>Certificate details of ${filesData['email']}</h3> 
        <p>URL: ${filesData['downloadURL']}</p>
        <p>Credits Awarded: ${filesData['points']}</p>
        
        <p>Tags: ${filesData['tags'].join(', ')}</p>
        <h5>This is an autogenerated email. Do not reply.</h5>
      ''';

    try {
      final sendReport = await send(message, smtpServer);
      print('Message sent: ' + sendReport.toString());
    } on MailerException catch (e) {
      print('Message not sent. ${e.message}');
      for (var p in e.problems) {
        print('Problem: ${p.code}: ${p.msg}');
      }
    }
  }

  Future<void> getEmailAndPassword() async {
    FirebaseFirestore firestore = FirebaseFirestore.instance;

    try {
      DocumentSnapshot documentSnapshot =
          await firestore.collection('adminemail').doc('elitesemail').get();

      if (documentSnapshot.exists) {
        String email = documentSnapshot.get('email');
        String password = documentSnapshot.get('password');
        print("hello1" + email);
        print("hello2" + password);
        await sendersEmailid(email, password);
      } else {
        print('Document does not exist');
      }
    } catch (e) {
      print('Error fetching email and password: $e');
    }
  }

  Future<void> sendersEmailid(String email, String password) async {
    FirebaseFirestore firestore = FirebaseFirestore.instance;

    try {
      DocumentSnapshot recipientSnapshot =
          await firestore.collection('adminemail').doc('AdminEmails').get();

      if (recipientSnapshot.exists) {
        String recipientEmail = recipientSnapshot.get('email');
        print("hello3" + recipientEmail);

        // Set the recipient email in filesData

        // Send the email directly
        print(filesData);
        await sendEmail(email, password, recipientEmail);
      } else {
        print('Recipient document does not exist');
      }
    } catch (e) {
      print('Error fetching email and password: $e');
    }
  }
}
